INSERT INTO OPERATION_TYPE (ID, DESCRIPTION, ENTRY) VALUES (1, 'COMPRA À VISTA', 'DEBIT');
INSERT INTO OPERATION_TYPE (ID, DESCRIPTION, ENTRY) VALUES (2, 'COMPRA PARCELADA', 'DEBIT');
INSERT INTO OPERATION_TYPE (ID, DESCRIPTION, ENTRY) VALUES (3, 'SAQUE', 'DEBIT');
INSERT INTO OPERATION_TYPE (ID, DESCRIPTION, ENTRY) VALUES (4, 'PAGAMENTO', 'CREDIT');
